// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scouting_data.proto

#include "scouting_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR MatchData::MatchData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.scout_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.event_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.notes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.match_level_)*/0
  , /*decltype(_impl_.match_number_)*/0u
  , /*decltype(_impl_.match_slot_)*/0
  , /*decltype(_impl_.team_number_)*/0u
  , /*decltype(_impl_.auto_start_position_)*/0u
  , /*decltype(_impl_.auto_fuel_)*/0u
  , /*decltype(_impl_.auto_neutral_zone_pass_)*/0u
  , /*decltype(_impl_.auto_climb_)*/0
  , /*decltype(_impl_.auto_depot_pickup_)*/false
  , /*decltype(_impl_.auto_outpost_pickup_)*/false
  , /*decltype(_impl_.auto_neutral_zone_pickup_)*/false
  , /*decltype(_impl_.teleop_depot_pickup_)*/false
  , /*decltype(_impl_.teleop_shooting_locations_)*/0u
  , /*decltype(_impl_.teleop_fuel_)*/0u
  , /*decltype(_impl_.teleop_neutral_zone_pass_)*/0u
  , /*decltype(_impl_.teleop_opponent_zone_pass_)*/0u
  , /*decltype(_impl_.teleop_outpost_pickup_)*/false
  , /*decltype(_impl_.teleop_neutral_zone_pickup_)*/false
  , /*decltype(_impl_.teleop_floor_pickup_)*/false
  , /*decltype(_impl_.crossed_bump_)*/false
  , /*decltype(_impl_.endgame_climb_)*/0
  , /*decltype(_impl_.driver_skill_)*/0
  , /*decltype(_impl_.defensive_skill_)*/0
  , /*decltype(_impl_.robot_speed_)*/0
  , /*decltype(_impl_.crosssed_trench_)*/false
  , /*decltype(_impl_.immobilized_)*/false
  , /*decltype(_impl_.tippy_)*/false
  , /*decltype(_impl_.good_partner_)*/false
  , /*decltype(_impl_.was_defended_)*/false
  , /*decltype(_impl_.excessive_penalties_)*/false
  , /*decltype(_impl_.fuel_percentage_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MatchDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MatchDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MatchDataDefaultTypeInternal() {}
  union {
    MatchData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MatchDataDefaultTypeInternal _MatchData_default_instance_;
PROTOBUF_CONSTEXPR CompetitionDataSet::CompetitionDataSet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.matches_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CompetitionDataSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompetitionDataSetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompetitionDataSetDefaultTypeInternal() {}
  union {
    CompetitionDataSet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompetitionDataSetDefaultTypeInternal _CompetitionDataSet_default_instance_;
static ::_pb::Metadata file_level_metadata_scouting_5fdata_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_scouting_5fdata_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_scouting_5fdata_2eproto = nullptr;

const uint32_t TableStruct_scouting_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MatchData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.scout_name_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.event_name_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.match_level_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.match_number_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.match_slot_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.team_number_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_start_position_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_fuel_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_neutral_zone_pass_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_climb_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_depot_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_outpost_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.auto_neutral_zone_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_shooting_locations_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_fuel_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_neutral_zone_pass_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_opponent_zone_pass_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_depot_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_outpost_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_neutral_zone_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.teleop_floor_pickup_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.endgame_climb_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.driver_skill_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.defensive_skill_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.robot_speed_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.crossed_bump_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.crosssed_trench_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.immobilized_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.tippy_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.good_partner_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.was_defended_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.excessive_penalties_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.fuel_percentage_),
  PROTOBUF_FIELD_OFFSET(::MatchData, _impl_.notes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CompetitionDataSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CompetitionDataSet, _impl_.matches_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MatchData)},
  { 40, -1, -1, sizeof(::CompetitionDataSet)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_MatchData_default_instance_._instance,
  &::_CompetitionDataSet_default_instance_._instance,
};

const char descriptor_table_protodef_scouting_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023scouting_data.proto\"\274\007\n\tMatchData\022\022\n\ns"
  "cout_name\030\001 \001(\t\022\022\n\nevent_name\030\002 \001(\t\022 \n\013m"
  "atch_level\030\003 \001(\0162\013.MatchLevel\022\024\n\014match_n"
  "umber\030\004 \001(\r\022\036\n\nmatch_slot\030\005 \001(\0162\n.MatchS"
  "lot\022\023\n\013team_number\030\006 \001(\r\022\033\n\023auto_start_p"
  "osition\030\007 \001(\r\022\021\n\tauto_fuel\030\010 \001(\r\022\036\n\026auto"
  "_neutral_zone_pass\030\t \001(\r\022\036\n\nauto_climb\030\n"
  " \001(\0162\n.AutoClimb\022\031\n\021auto_depot_pickup\030\013 "
  "\001(\010\022\033\n\023auto_outpost_pickup\030\014 \001(\010\022 \n\030auto"
  "_neutral_zone_pickup\030\r \001(\010\022!\n\031teleop_sho"
  "oting_locations\030\016 \001(\r\022\023\n\013teleop_fuel\030\017 \001"
  "(\r\022 \n\030teleop_neutral_zone_pass\030\020 \001(\r\022!\n\031"
  "teleop_opponent_zone_pass\030\021 \001(\r\022\033\n\023teleo"
  "p_depot_pickup\030\022 \001(\010\022\035\n\025teleop_outpost_p"
  "ickup\030\023 \001(\010\022\"\n\032teleop_neutral_zone_picku"
  "p\030\024 \001(\010\022\033\n\023teleop_floor_pickup\030\025 \001(\010\022$\n\r"
  "endgame_climb\030\026 \001(\0162\r.EndgameClimb\022\"\n\014dr"
  "iver_skill\030\027 \001(\0162\014.SkillRating\022%\n\017defens"
  "ive_skill\030\030 \001(\0162\014.SkillRating\022!\n\013robot_s"
  "peed\030\031 \001(\0162\014.SkillRating\022\024\n\014crossed_bump"
  "\030\032 \001(\010\022\027\n\017crosssed_trench\030\033 \001(\010\022\023\n\013immob"
  "ilized\030\034 \001(\010\022\r\n\005tippy\030\035 \001(\010\022\024\n\014good_part"
  "ner\030\036 \001(\010\022\024\n\014was_defended\030\037 \001(\010\022\033\n\023exces"
  "sive_penalties\030  \001(\010\022\027\n\017fuel_percentage\030"
  "! \001(\r\022\r\n\005notes\030\" \001(\t\"1\n\022CompetitionDataS"
  "et\022\033\n\007matches\030\001 \003(\0132\n.MatchData*P\n\tMatch"
  "Slot\022\t\n\005RED_1\020\000\022\t\n\005RED_2\020\001\022\t\n\005RED_3\020\002\022\n\n"
  "\006BLUE_1\020\003\022\n\n\006BLUE_2\020\004\022\n\n\006BLUE_3\020\005*:\n\nMat"
  "chLevel\022\021\n\rQUALIFICATION\020\000\022\016\n\nSEMI_FINAL"
  "\020\001\022\t\n\005FINAL\020\002*P\n\tAutoClimb\022\013\n\007CLIMBED\020\000\022"
  "\030\n\024AUTO_CLIMB_ATTEMPTED\020\001\022\034\n\030AUTO_CLIMB_"
  "NOT_ATTEMPTED\020\002*s\n\014EndgameClimb\022\013\n\007LEVEL"
  "_1\020\000\022\013\n\007LEVEL_2\020\001\022\013\n\007LEVEL_3\020\002\022\033\n\027ENDGAM"
  "E_CLIMB_ATTEMPTED\020\003\022\037\n\033ENDGAME_CLIMB_NOT"
  "_ATTEMPTED\020\004*O\n\013SkillRating\022\021\n\rBELOW_AVE"
  "RAGE\020\000\022\013\n\007AVERAGE\020\001\022\021\n\rABOVE_AVERAGE\020\002\022\r"
  "\n\tNOT_RATED\020\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_scouting_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_scouting_5fdata_2eproto = {
    false, false, 1461, descriptor_table_protodef_scouting_5fdata_2eproto,
    "scouting_data.proto",
    &descriptor_table_scouting_5fdata_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_scouting_5fdata_2eproto::offsets,
    file_level_metadata_scouting_5fdata_2eproto, file_level_enum_descriptors_scouting_5fdata_2eproto,
    file_level_service_descriptors_scouting_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_scouting_5fdata_2eproto_getter() {
  return &descriptor_table_scouting_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_scouting_5fdata_2eproto(&descriptor_table_scouting_5fdata_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MatchSlot_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_scouting_5fdata_2eproto);
  return file_level_enum_descriptors_scouting_5fdata_2eproto[0];
}
bool MatchSlot_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MatchLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_scouting_5fdata_2eproto);
  return file_level_enum_descriptors_scouting_5fdata_2eproto[1];
}
bool MatchLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AutoClimb_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_scouting_5fdata_2eproto);
  return file_level_enum_descriptors_scouting_5fdata_2eproto[2];
}
bool AutoClimb_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EndgameClimb_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_scouting_5fdata_2eproto);
  return file_level_enum_descriptors_scouting_5fdata_2eproto[3];
}
bool EndgameClimb_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SkillRating_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_scouting_5fdata_2eproto);
  return file_level_enum_descriptors_scouting_5fdata_2eproto[4];
}
bool SkillRating_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class MatchData::_Internal {
 public:
};

MatchData::MatchData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MatchData)
}
MatchData::MatchData(const MatchData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MatchData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.scout_name_){}
    , decltype(_impl_.event_name_){}
    , decltype(_impl_.notes_){}
    , decltype(_impl_.match_level_){}
    , decltype(_impl_.match_number_){}
    , decltype(_impl_.match_slot_){}
    , decltype(_impl_.team_number_){}
    , decltype(_impl_.auto_start_position_){}
    , decltype(_impl_.auto_fuel_){}
    , decltype(_impl_.auto_neutral_zone_pass_){}
    , decltype(_impl_.auto_climb_){}
    , decltype(_impl_.auto_depot_pickup_){}
    , decltype(_impl_.auto_outpost_pickup_){}
    , decltype(_impl_.auto_neutral_zone_pickup_){}
    , decltype(_impl_.teleop_depot_pickup_){}
    , decltype(_impl_.teleop_shooting_locations_){}
    , decltype(_impl_.teleop_fuel_){}
    , decltype(_impl_.teleop_neutral_zone_pass_){}
    , decltype(_impl_.teleop_opponent_zone_pass_){}
    , decltype(_impl_.teleop_outpost_pickup_){}
    , decltype(_impl_.teleop_neutral_zone_pickup_){}
    , decltype(_impl_.teleop_floor_pickup_){}
    , decltype(_impl_.crossed_bump_){}
    , decltype(_impl_.endgame_climb_){}
    , decltype(_impl_.driver_skill_){}
    , decltype(_impl_.defensive_skill_){}
    , decltype(_impl_.robot_speed_){}
    , decltype(_impl_.crosssed_trench_){}
    , decltype(_impl_.immobilized_){}
    , decltype(_impl_.tippy_){}
    , decltype(_impl_.good_partner_){}
    , decltype(_impl_.was_defended_){}
    , decltype(_impl_.excessive_penalties_){}
    , decltype(_impl_.fuel_percentage_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.scout_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scout_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_scout_name().empty()) {
    _this->_impl_.scout_name_.Set(from._internal_scout_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.event_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.event_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_event_name().empty()) {
    _this->_impl_.event_name_.Set(from._internal_event_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.notes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.notes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_notes().empty()) {
    _this->_impl_.notes_.Set(from._internal_notes(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.match_level_, &from._impl_.match_level_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.fuel_percentage_) -
    reinterpret_cast<char*>(&_impl_.match_level_)) + sizeof(_impl_.fuel_percentage_));
  // @@protoc_insertion_point(copy_constructor:MatchData)
}

inline void MatchData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.scout_name_){}
    , decltype(_impl_.event_name_){}
    , decltype(_impl_.notes_){}
    , decltype(_impl_.match_level_){0}
    , decltype(_impl_.match_number_){0u}
    , decltype(_impl_.match_slot_){0}
    , decltype(_impl_.team_number_){0u}
    , decltype(_impl_.auto_start_position_){0u}
    , decltype(_impl_.auto_fuel_){0u}
    , decltype(_impl_.auto_neutral_zone_pass_){0u}
    , decltype(_impl_.auto_climb_){0}
    , decltype(_impl_.auto_depot_pickup_){false}
    , decltype(_impl_.auto_outpost_pickup_){false}
    , decltype(_impl_.auto_neutral_zone_pickup_){false}
    , decltype(_impl_.teleop_depot_pickup_){false}
    , decltype(_impl_.teleop_shooting_locations_){0u}
    , decltype(_impl_.teleop_fuel_){0u}
    , decltype(_impl_.teleop_neutral_zone_pass_){0u}
    , decltype(_impl_.teleop_opponent_zone_pass_){0u}
    , decltype(_impl_.teleop_outpost_pickup_){false}
    , decltype(_impl_.teleop_neutral_zone_pickup_){false}
    , decltype(_impl_.teleop_floor_pickup_){false}
    , decltype(_impl_.crossed_bump_){false}
    , decltype(_impl_.endgame_climb_){0}
    , decltype(_impl_.driver_skill_){0}
    , decltype(_impl_.defensive_skill_){0}
    , decltype(_impl_.robot_speed_){0}
    , decltype(_impl_.crosssed_trench_){false}
    , decltype(_impl_.immobilized_){false}
    , decltype(_impl_.tippy_){false}
    , decltype(_impl_.good_partner_){false}
    , decltype(_impl_.was_defended_){false}
    , decltype(_impl_.excessive_penalties_){false}
    , decltype(_impl_.fuel_percentage_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.scout_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scout_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.event_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.event_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.notes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.notes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MatchData::~MatchData() {
  // @@protoc_insertion_point(destructor:MatchData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MatchData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.scout_name_.Destroy();
  _impl_.event_name_.Destroy();
  _impl_.notes_.Destroy();
}

void MatchData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MatchData::Clear() {
// @@protoc_insertion_point(message_clear_start:MatchData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scout_name_.ClearToEmpty();
  _impl_.event_name_.ClearToEmpty();
  _impl_.notes_.ClearToEmpty();
  ::memset(&_impl_.match_level_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.fuel_percentage_) -
      reinterpret_cast<char*>(&_impl_.match_level_)) + sizeof(_impl_.fuel_percentage_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MatchData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string scout_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_scout_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "MatchData.scout_name"));
        } else
          goto handle_unusual;
        continue;
      // string event_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_event_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "MatchData.event_name"));
        } else
          goto handle_unusual;
        continue;
      // .MatchLevel match_level = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_match_level(static_cast<::MatchLevel>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 match_number = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.match_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .MatchSlot match_slot = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_match_slot(static_cast<::MatchSlot>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 team_number = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.team_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 auto_start_position = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.auto_start_position_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 auto_fuel = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.auto_fuel_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 auto_neutral_zone_pass = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.auto_neutral_zone_pass_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .AutoClimb auto_climb = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_auto_climb(static_cast<::AutoClimb>(val));
        } else
          goto handle_unusual;
        continue;
      // bool auto_depot_pickup = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.auto_depot_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool auto_outpost_pickup = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.auto_outpost_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool auto_neutral_zone_pickup = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          _impl_.auto_neutral_zone_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 teleop_shooting_locations = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _impl_.teleop_shooting_locations_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 teleop_fuel = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.teleop_fuel_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 teleop_neutral_zone_pass = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 128)) {
          _impl_.teleop_neutral_zone_pass_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 teleop_opponent_zone_pass = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 136)) {
          _impl_.teleop_opponent_zone_pass_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool teleop_depot_pickup = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          _impl_.teleop_depot_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool teleop_outpost_pickup = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 152)) {
          _impl_.teleop_outpost_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool teleop_neutral_zone_pickup = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 160)) {
          _impl_.teleop_neutral_zone_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool teleop_floor_pickup = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 168)) {
          _impl_.teleop_floor_pickup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .EndgameClimb endgame_climb = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 176)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_endgame_climb(static_cast<::EndgameClimb>(val));
        } else
          goto handle_unusual;
        continue;
      // .SkillRating driver_skill = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 184)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_driver_skill(static_cast<::SkillRating>(val));
        } else
          goto handle_unusual;
        continue;
      // .SkillRating defensive_skill = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 192)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_defensive_skill(static_cast<::SkillRating>(val));
        } else
          goto handle_unusual;
        continue;
      // .SkillRating robot_speed = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 200)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_robot_speed(static_cast<::SkillRating>(val));
        } else
          goto handle_unusual;
        continue;
      // bool crossed_bump = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 208)) {
          _impl_.crossed_bump_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool crosssed_trench = 27;
      case 27:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 216)) {
          _impl_.crosssed_trench_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool immobilized = 28;
      case 28:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 224)) {
          _impl_.immobilized_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool tippy = 29;
      case 29:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 232)) {
          _impl_.tippy_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool good_partner = 30;
      case 30:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 240)) {
          _impl_.good_partner_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool was_defended = 31;
      case 31:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 248)) {
          _impl_.was_defended_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool excessive_penalties = 32;
      case 32:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 0)) {
          _impl_.excessive_penalties_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 fuel_percentage = 33;
      case 33:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.fuel_percentage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string notes = 34;
      case 34:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_notes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "MatchData.notes"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MatchData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MatchData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string scout_name = 1;
  if (!this->_internal_scout_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scout_name().data(), static_cast<int>(this->_internal_scout_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MatchData.scout_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_scout_name(), target);
  }

  // string event_name = 2;
  if (!this->_internal_event_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_event_name().data(), static_cast<int>(this->_internal_event_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MatchData.event_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_event_name(), target);
  }

  // .MatchLevel match_level = 3;
  if (this->_internal_match_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_match_level(), target);
  }

  // uint32 match_number = 4;
  if (this->_internal_match_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_match_number(), target);
  }

  // .MatchSlot match_slot = 5;
  if (this->_internal_match_slot() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_match_slot(), target);
  }

  // uint32 team_number = 6;
  if (this->_internal_team_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_team_number(), target);
  }

  // uint32 auto_start_position = 7;
  if (this->_internal_auto_start_position() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_auto_start_position(), target);
  }

  // uint32 auto_fuel = 8;
  if (this->_internal_auto_fuel() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_auto_fuel(), target);
  }

  // uint32 auto_neutral_zone_pass = 9;
  if (this->_internal_auto_neutral_zone_pass() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_auto_neutral_zone_pass(), target);
  }

  // .AutoClimb auto_climb = 10;
  if (this->_internal_auto_climb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      10, this->_internal_auto_climb(), target);
  }

  // bool auto_depot_pickup = 11;
  if (this->_internal_auto_depot_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(11, this->_internal_auto_depot_pickup(), target);
  }

  // bool auto_outpost_pickup = 12;
  if (this->_internal_auto_outpost_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(12, this->_internal_auto_outpost_pickup(), target);
  }

  // bool auto_neutral_zone_pickup = 13;
  if (this->_internal_auto_neutral_zone_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(13, this->_internal_auto_neutral_zone_pickup(), target);
  }

  // uint32 teleop_shooting_locations = 14;
  if (this->_internal_teleop_shooting_locations() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(14, this->_internal_teleop_shooting_locations(), target);
  }

  // uint32 teleop_fuel = 15;
  if (this->_internal_teleop_fuel() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(15, this->_internal_teleop_fuel(), target);
  }

  // uint32 teleop_neutral_zone_pass = 16;
  if (this->_internal_teleop_neutral_zone_pass() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(16, this->_internal_teleop_neutral_zone_pass(), target);
  }

  // uint32 teleop_opponent_zone_pass = 17;
  if (this->_internal_teleop_opponent_zone_pass() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(17, this->_internal_teleop_opponent_zone_pass(), target);
  }

  // bool teleop_depot_pickup = 18;
  if (this->_internal_teleop_depot_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(18, this->_internal_teleop_depot_pickup(), target);
  }

  // bool teleop_outpost_pickup = 19;
  if (this->_internal_teleop_outpost_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(19, this->_internal_teleop_outpost_pickup(), target);
  }

  // bool teleop_neutral_zone_pickup = 20;
  if (this->_internal_teleop_neutral_zone_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(20, this->_internal_teleop_neutral_zone_pickup(), target);
  }

  // bool teleop_floor_pickup = 21;
  if (this->_internal_teleop_floor_pickup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(21, this->_internal_teleop_floor_pickup(), target);
  }

  // .EndgameClimb endgame_climb = 22;
  if (this->_internal_endgame_climb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      22, this->_internal_endgame_climb(), target);
  }

  // .SkillRating driver_skill = 23;
  if (this->_internal_driver_skill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      23, this->_internal_driver_skill(), target);
  }

  // .SkillRating defensive_skill = 24;
  if (this->_internal_defensive_skill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      24, this->_internal_defensive_skill(), target);
  }

  // .SkillRating robot_speed = 25;
  if (this->_internal_robot_speed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      25, this->_internal_robot_speed(), target);
  }

  // bool crossed_bump = 26;
  if (this->_internal_crossed_bump() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(26, this->_internal_crossed_bump(), target);
  }

  // bool crosssed_trench = 27;
  if (this->_internal_crosssed_trench() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(27, this->_internal_crosssed_trench(), target);
  }

  // bool immobilized = 28;
  if (this->_internal_immobilized() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(28, this->_internal_immobilized(), target);
  }

  // bool tippy = 29;
  if (this->_internal_tippy() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(29, this->_internal_tippy(), target);
  }

  // bool good_partner = 30;
  if (this->_internal_good_partner() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(30, this->_internal_good_partner(), target);
  }

  // bool was_defended = 31;
  if (this->_internal_was_defended() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(31, this->_internal_was_defended(), target);
  }

  // bool excessive_penalties = 32;
  if (this->_internal_excessive_penalties() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(32, this->_internal_excessive_penalties(), target);
  }

  // uint32 fuel_percentage = 33;
  if (this->_internal_fuel_percentage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(33, this->_internal_fuel_percentage(), target);
  }

  // string notes = 34;
  if (!this->_internal_notes().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_notes().data(), static_cast<int>(this->_internal_notes().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MatchData.notes");
    target = stream->WriteStringMaybeAliased(
        34, this->_internal_notes(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MatchData)
  return target;
}

size_t MatchData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MatchData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string scout_name = 1;
  if (!this->_internal_scout_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scout_name());
  }

  // string event_name = 2;
  if (!this->_internal_event_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_event_name());
  }

  // string notes = 34;
  if (!this->_internal_notes().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_notes());
  }

  // .MatchLevel match_level = 3;
  if (this->_internal_match_level() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_match_level());
  }

  // uint32 match_number = 4;
  if (this->_internal_match_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_match_number());
  }

  // .MatchSlot match_slot = 5;
  if (this->_internal_match_slot() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_match_slot());
  }

  // uint32 team_number = 6;
  if (this->_internal_team_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_team_number());
  }

  // uint32 auto_start_position = 7;
  if (this->_internal_auto_start_position() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_auto_start_position());
  }

  // uint32 auto_fuel = 8;
  if (this->_internal_auto_fuel() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_auto_fuel());
  }

  // uint32 auto_neutral_zone_pass = 9;
  if (this->_internal_auto_neutral_zone_pass() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_auto_neutral_zone_pass());
  }

  // .AutoClimb auto_climb = 10;
  if (this->_internal_auto_climb() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_auto_climb());
  }

  // bool auto_depot_pickup = 11;
  if (this->_internal_auto_depot_pickup() != 0) {
    total_size += 1 + 1;
  }

  // bool auto_outpost_pickup = 12;
  if (this->_internal_auto_outpost_pickup() != 0) {
    total_size += 1 + 1;
  }

  // bool auto_neutral_zone_pickup = 13;
  if (this->_internal_auto_neutral_zone_pickup() != 0) {
    total_size += 1 + 1;
  }

  // bool teleop_depot_pickup = 18;
  if (this->_internal_teleop_depot_pickup() != 0) {
    total_size += 2 + 1;
  }

  // uint32 teleop_shooting_locations = 14;
  if (this->_internal_teleop_shooting_locations() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_teleop_shooting_locations());
  }

  // uint32 teleop_fuel = 15;
  if (this->_internal_teleop_fuel() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_teleop_fuel());
  }

  // uint32 teleop_neutral_zone_pass = 16;
  if (this->_internal_teleop_neutral_zone_pass() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_teleop_neutral_zone_pass());
  }

  // uint32 teleop_opponent_zone_pass = 17;
  if (this->_internal_teleop_opponent_zone_pass() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_teleop_opponent_zone_pass());
  }

  // bool teleop_outpost_pickup = 19;
  if (this->_internal_teleop_outpost_pickup() != 0) {
    total_size += 2 + 1;
  }

  // bool teleop_neutral_zone_pickup = 20;
  if (this->_internal_teleop_neutral_zone_pickup() != 0) {
    total_size += 2 + 1;
  }

  // bool teleop_floor_pickup = 21;
  if (this->_internal_teleop_floor_pickup() != 0) {
    total_size += 2 + 1;
  }

  // bool crossed_bump = 26;
  if (this->_internal_crossed_bump() != 0) {
    total_size += 2 + 1;
  }

  // .EndgameClimb endgame_climb = 22;
  if (this->_internal_endgame_climb() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_endgame_climb());
  }

  // .SkillRating driver_skill = 23;
  if (this->_internal_driver_skill() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_driver_skill());
  }

  // .SkillRating defensive_skill = 24;
  if (this->_internal_defensive_skill() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_defensive_skill());
  }

  // .SkillRating robot_speed = 25;
  if (this->_internal_robot_speed() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_robot_speed());
  }

  // bool crosssed_trench = 27;
  if (this->_internal_crosssed_trench() != 0) {
    total_size += 2 + 1;
  }

  // bool immobilized = 28;
  if (this->_internal_immobilized() != 0) {
    total_size += 2 + 1;
  }

  // bool tippy = 29;
  if (this->_internal_tippy() != 0) {
    total_size += 2 + 1;
  }

  // bool good_partner = 30;
  if (this->_internal_good_partner() != 0) {
    total_size += 2 + 1;
  }

  // bool was_defended = 31;
  if (this->_internal_was_defended() != 0) {
    total_size += 2 + 1;
  }

  // bool excessive_penalties = 32;
  if (this->_internal_excessive_penalties() != 0) {
    total_size += 2 + 1;
  }

  // uint32 fuel_percentage = 33;
  if (this->_internal_fuel_percentage() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_fuel_percentage());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MatchData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MatchData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MatchData::GetClassData() const { return &_class_data_; }


void MatchData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MatchData*>(&to_msg);
  auto& from = static_cast<const MatchData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MatchData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_scout_name().empty()) {
    _this->_internal_set_scout_name(from._internal_scout_name());
  }
  if (!from._internal_event_name().empty()) {
    _this->_internal_set_event_name(from._internal_event_name());
  }
  if (!from._internal_notes().empty()) {
    _this->_internal_set_notes(from._internal_notes());
  }
  if (from._internal_match_level() != 0) {
    _this->_internal_set_match_level(from._internal_match_level());
  }
  if (from._internal_match_number() != 0) {
    _this->_internal_set_match_number(from._internal_match_number());
  }
  if (from._internal_match_slot() != 0) {
    _this->_internal_set_match_slot(from._internal_match_slot());
  }
  if (from._internal_team_number() != 0) {
    _this->_internal_set_team_number(from._internal_team_number());
  }
  if (from._internal_auto_start_position() != 0) {
    _this->_internal_set_auto_start_position(from._internal_auto_start_position());
  }
  if (from._internal_auto_fuel() != 0) {
    _this->_internal_set_auto_fuel(from._internal_auto_fuel());
  }
  if (from._internal_auto_neutral_zone_pass() != 0) {
    _this->_internal_set_auto_neutral_zone_pass(from._internal_auto_neutral_zone_pass());
  }
  if (from._internal_auto_climb() != 0) {
    _this->_internal_set_auto_climb(from._internal_auto_climb());
  }
  if (from._internal_auto_depot_pickup() != 0) {
    _this->_internal_set_auto_depot_pickup(from._internal_auto_depot_pickup());
  }
  if (from._internal_auto_outpost_pickup() != 0) {
    _this->_internal_set_auto_outpost_pickup(from._internal_auto_outpost_pickup());
  }
  if (from._internal_auto_neutral_zone_pickup() != 0) {
    _this->_internal_set_auto_neutral_zone_pickup(from._internal_auto_neutral_zone_pickup());
  }
  if (from._internal_teleop_depot_pickup() != 0) {
    _this->_internal_set_teleop_depot_pickup(from._internal_teleop_depot_pickup());
  }
  if (from._internal_teleop_shooting_locations() != 0) {
    _this->_internal_set_teleop_shooting_locations(from._internal_teleop_shooting_locations());
  }
  if (from._internal_teleop_fuel() != 0) {
    _this->_internal_set_teleop_fuel(from._internal_teleop_fuel());
  }
  if (from._internal_teleop_neutral_zone_pass() != 0) {
    _this->_internal_set_teleop_neutral_zone_pass(from._internal_teleop_neutral_zone_pass());
  }
  if (from._internal_teleop_opponent_zone_pass() != 0) {
    _this->_internal_set_teleop_opponent_zone_pass(from._internal_teleop_opponent_zone_pass());
  }
  if (from._internal_teleop_outpost_pickup() != 0) {
    _this->_internal_set_teleop_outpost_pickup(from._internal_teleop_outpost_pickup());
  }
  if (from._internal_teleop_neutral_zone_pickup() != 0) {
    _this->_internal_set_teleop_neutral_zone_pickup(from._internal_teleop_neutral_zone_pickup());
  }
  if (from._internal_teleop_floor_pickup() != 0) {
    _this->_internal_set_teleop_floor_pickup(from._internal_teleop_floor_pickup());
  }
  if (from._internal_crossed_bump() != 0) {
    _this->_internal_set_crossed_bump(from._internal_crossed_bump());
  }
  if (from._internal_endgame_climb() != 0) {
    _this->_internal_set_endgame_climb(from._internal_endgame_climb());
  }
  if (from._internal_driver_skill() != 0) {
    _this->_internal_set_driver_skill(from._internal_driver_skill());
  }
  if (from._internal_defensive_skill() != 0) {
    _this->_internal_set_defensive_skill(from._internal_defensive_skill());
  }
  if (from._internal_robot_speed() != 0) {
    _this->_internal_set_robot_speed(from._internal_robot_speed());
  }
  if (from._internal_crosssed_trench() != 0) {
    _this->_internal_set_crosssed_trench(from._internal_crosssed_trench());
  }
  if (from._internal_immobilized() != 0) {
    _this->_internal_set_immobilized(from._internal_immobilized());
  }
  if (from._internal_tippy() != 0) {
    _this->_internal_set_tippy(from._internal_tippy());
  }
  if (from._internal_good_partner() != 0) {
    _this->_internal_set_good_partner(from._internal_good_partner());
  }
  if (from._internal_was_defended() != 0) {
    _this->_internal_set_was_defended(from._internal_was_defended());
  }
  if (from._internal_excessive_penalties() != 0) {
    _this->_internal_set_excessive_penalties(from._internal_excessive_penalties());
  }
  if (from._internal_fuel_percentage() != 0) {
    _this->_internal_set_fuel_percentage(from._internal_fuel_percentage());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MatchData::CopyFrom(const MatchData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MatchData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatchData::IsInitialized() const {
  return true;
}

void MatchData::InternalSwap(MatchData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.scout_name_, lhs_arena,
      &other->_impl_.scout_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.event_name_, lhs_arena,
      &other->_impl_.event_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.notes_, lhs_arena,
      &other->_impl_.notes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MatchData, _impl_.fuel_percentage_)
      + sizeof(MatchData::_impl_.fuel_percentage_)
      - PROTOBUF_FIELD_OFFSET(MatchData, _impl_.match_level_)>(
          reinterpret_cast<char*>(&_impl_.match_level_),
          reinterpret_cast<char*>(&other->_impl_.match_level_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MatchData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scouting_5fdata_2eproto_getter, &descriptor_table_scouting_5fdata_2eproto_once,
      file_level_metadata_scouting_5fdata_2eproto[0]);
}

// ===================================================================

class CompetitionDataSet::_Internal {
 public:
};

CompetitionDataSet::CompetitionDataSet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CompetitionDataSet)
}
CompetitionDataSet::CompetitionDataSet(const CompetitionDataSet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CompetitionDataSet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.matches_){from._impl_.matches_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CompetitionDataSet)
}

inline void CompetitionDataSet::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.matches_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CompetitionDataSet::~CompetitionDataSet() {
  // @@protoc_insertion_point(destructor:CompetitionDataSet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CompetitionDataSet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.matches_.~RepeatedPtrField();
}

void CompetitionDataSet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CompetitionDataSet::Clear() {
// @@protoc_insertion_point(message_clear_start:CompetitionDataSet)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.matches_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CompetitionDataSet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .MatchData matches = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_matches(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CompetitionDataSet::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CompetitionDataSet)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MatchData matches = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_matches_size()); i < n; i++) {
    const auto& repfield = this->_internal_matches(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CompetitionDataSet)
  return target;
}

size_t CompetitionDataSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CompetitionDataSet)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .MatchData matches = 1;
  total_size += 1UL * this->_internal_matches_size();
  for (const auto& msg : this->_impl_.matches_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CompetitionDataSet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CompetitionDataSet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CompetitionDataSet::GetClassData() const { return &_class_data_; }


void CompetitionDataSet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CompetitionDataSet*>(&to_msg);
  auto& from = static_cast<const CompetitionDataSet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CompetitionDataSet)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.matches_.MergeFrom(from._impl_.matches_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CompetitionDataSet::CopyFrom(const CompetitionDataSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CompetitionDataSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompetitionDataSet::IsInitialized() const {
  return true;
}

void CompetitionDataSet::InternalSwap(CompetitionDataSet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.matches_.InternalSwap(&other->_impl_.matches_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CompetitionDataSet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_scouting_5fdata_2eproto_getter, &descriptor_table_scouting_5fdata_2eproto_once,
      file_level_metadata_scouting_5fdata_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MatchData*
Arena::CreateMaybeMessage< ::MatchData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MatchData >(arena);
}
template<> PROTOBUF_NOINLINE ::CompetitionDataSet*
Arena::CreateMaybeMessage< ::CompetitionDataSet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CompetitionDataSet >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
