// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scouting_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_scouting_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_scouting_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_scouting_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_scouting_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_scouting_5fdata_2eproto;
class CompetitionDataSet;
struct CompetitionDataSetDefaultTypeInternal;
extern CompetitionDataSetDefaultTypeInternal _CompetitionDataSet_default_instance_;
class MatchData;
struct MatchDataDefaultTypeInternal;
extern MatchDataDefaultTypeInternal _MatchData_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CompetitionDataSet* Arena::CreateMaybeMessage<::CompetitionDataSet>(Arena*);
template<> ::MatchData* Arena::CreateMaybeMessage<::MatchData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum MatchSlot : int {
  RED_1 = 0,
  RED_2 = 1,
  RED_3 = 2,
  BLUE_1 = 3,
  BLUE_2 = 4,
  BLUE_3 = 5,
  MatchSlot_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MatchSlot_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MatchSlot_IsValid(int value);
constexpr MatchSlot MatchSlot_MIN = RED_1;
constexpr MatchSlot MatchSlot_MAX = BLUE_3;
constexpr int MatchSlot_ARRAYSIZE = MatchSlot_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MatchSlot_descriptor();
template<typename T>
inline const std::string& MatchSlot_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MatchSlot>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MatchSlot_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MatchSlot_descriptor(), enum_t_value);
}
inline bool MatchSlot_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MatchSlot* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MatchSlot>(
    MatchSlot_descriptor(), name, value);
}
enum MatchLevel : int {
  QUALIFICATION = 0,
  SEMI_FINAL = 1,
  FINAL = 2,
  MatchLevel_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MatchLevel_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MatchLevel_IsValid(int value);
constexpr MatchLevel MatchLevel_MIN = QUALIFICATION;
constexpr MatchLevel MatchLevel_MAX = FINAL;
constexpr int MatchLevel_ARRAYSIZE = MatchLevel_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MatchLevel_descriptor();
template<typename T>
inline const std::string& MatchLevel_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MatchLevel>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MatchLevel_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MatchLevel_descriptor(), enum_t_value);
}
inline bool MatchLevel_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MatchLevel* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MatchLevel>(
    MatchLevel_descriptor(), name, value);
}
enum AutoClimb : int {
  CLIMBED = 0,
  AUTO_CLIMB_ATTEMPTED = 1,
  AUTO_CLIMB_NOT_ATTEMPTED = 2,
  AutoClimb_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AutoClimb_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AutoClimb_IsValid(int value);
constexpr AutoClimb AutoClimb_MIN = CLIMBED;
constexpr AutoClimb AutoClimb_MAX = AUTO_CLIMB_NOT_ATTEMPTED;
constexpr int AutoClimb_ARRAYSIZE = AutoClimb_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AutoClimb_descriptor();
template<typename T>
inline const std::string& AutoClimb_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AutoClimb>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AutoClimb_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AutoClimb_descriptor(), enum_t_value);
}
inline bool AutoClimb_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AutoClimb* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AutoClimb>(
    AutoClimb_descriptor(), name, value);
}
enum EndgameClimb : int {
  LEVEL_1 = 0,
  LEVEL_2 = 1,
  LEVEL_3 = 2,
  ENDGAME_CLIMB_ATTEMPTED = 3,
  ENDGAME_CLIMB_NOT_ATTEMPTED = 4,
  EndgameClimb_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EndgameClimb_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EndgameClimb_IsValid(int value);
constexpr EndgameClimb EndgameClimb_MIN = LEVEL_1;
constexpr EndgameClimb EndgameClimb_MAX = ENDGAME_CLIMB_NOT_ATTEMPTED;
constexpr int EndgameClimb_ARRAYSIZE = EndgameClimb_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EndgameClimb_descriptor();
template<typename T>
inline const std::string& EndgameClimb_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EndgameClimb>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EndgameClimb_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EndgameClimb_descriptor(), enum_t_value);
}
inline bool EndgameClimb_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EndgameClimb* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EndgameClimb>(
    EndgameClimb_descriptor(), name, value);
}
enum SkillRating : int {
  BELOW_AVERAGE = 0,
  AVERAGE = 1,
  ABOVE_AVERAGE = 2,
  NOT_RATED = 3,
  SkillRating_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SkillRating_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SkillRating_IsValid(int value);
constexpr SkillRating SkillRating_MIN = BELOW_AVERAGE;
constexpr SkillRating SkillRating_MAX = NOT_RATED;
constexpr int SkillRating_ARRAYSIZE = SkillRating_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SkillRating_descriptor();
template<typename T>
inline const std::string& SkillRating_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SkillRating>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SkillRating_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SkillRating_descriptor(), enum_t_value);
}
inline bool SkillRating_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SkillRating* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SkillRating>(
    SkillRating_descriptor(), name, value);
}
// ===================================================================

class MatchData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MatchData) */ {
 public:
  inline MatchData() : MatchData(nullptr) {}
  ~MatchData() override;
  explicit PROTOBUF_CONSTEXPR MatchData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MatchData(const MatchData& from);
  MatchData(MatchData&& from) noexcept
    : MatchData() {
    *this = ::std::move(from);
  }

  inline MatchData& operator=(const MatchData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchData& operator=(MatchData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchData& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatchData* internal_default_instance() {
    return reinterpret_cast<const MatchData*>(
               &_MatchData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MatchData& a, MatchData& b) {
    a.Swap(&b);
  }
  inline void Swap(MatchData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatchData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MatchData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MatchData& from) {
    MatchData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatchData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MatchData";
  }
  protected:
  explicit MatchData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScoutNameFieldNumber = 1,
    kEventNameFieldNumber = 2,
    kNotesFieldNumber = 34,
    kMatchLevelFieldNumber = 3,
    kMatchNumberFieldNumber = 4,
    kMatchSlotFieldNumber = 5,
    kTeamNumberFieldNumber = 6,
    kAutoStartPositionFieldNumber = 7,
    kAutoFuelFieldNumber = 8,
    kAutoNeutralZonePassFieldNumber = 9,
    kAutoClimbFieldNumber = 10,
    kAutoDepotPickupFieldNumber = 11,
    kAutoOutpostPickupFieldNumber = 12,
    kAutoNeutralZonePickupFieldNumber = 13,
    kTeleopDepotPickupFieldNumber = 18,
    kTeleopShootingLocationsFieldNumber = 14,
    kTeleopFuelFieldNumber = 15,
    kTeleopNeutralZonePassFieldNumber = 16,
    kTeleopOpponentZonePassFieldNumber = 17,
    kTeleopOutpostPickupFieldNumber = 19,
    kTeleopNeutralZonePickupFieldNumber = 20,
    kTeleopFloorPickupFieldNumber = 21,
    kCrossedBumpFieldNumber = 26,
    kEndgameClimbFieldNumber = 22,
    kDriverSkillFieldNumber = 23,
    kDefensiveSkillFieldNumber = 24,
    kRobotSpeedFieldNumber = 25,
    kCrosssedTrenchFieldNumber = 27,
    kImmobilizedFieldNumber = 28,
    kTippyFieldNumber = 29,
    kGoodPartnerFieldNumber = 30,
    kWasDefendedFieldNumber = 31,
    kExcessivePenaltiesFieldNumber = 32,
    kFuelPercentageFieldNumber = 33,
  };
  // string scout_name = 1;
  void clear_scout_name();
  const std::string& scout_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_scout_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_scout_name();
  PROTOBUF_NODISCARD std::string* release_scout_name();
  void set_allocated_scout_name(std::string* scout_name);
  private:
  const std::string& _internal_scout_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_scout_name(const std::string& value);
  std::string* _internal_mutable_scout_name();
  public:

  // string event_name = 2;
  void clear_event_name();
  const std::string& event_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_event_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_event_name();
  PROTOBUF_NODISCARD std::string* release_event_name();
  void set_allocated_event_name(std::string* event_name);
  private:
  const std::string& _internal_event_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_event_name(const std::string& value);
  std::string* _internal_mutable_event_name();
  public:

  // string notes = 34;
  void clear_notes();
  const std::string& notes() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_notes(ArgT0&& arg0, ArgT... args);
  std::string* mutable_notes();
  PROTOBUF_NODISCARD std::string* release_notes();
  void set_allocated_notes(std::string* notes);
  private:
  const std::string& _internal_notes() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_notes(const std::string& value);
  std::string* _internal_mutable_notes();
  public:

  // .MatchLevel match_level = 3;
  void clear_match_level();
  ::MatchLevel match_level() const;
  void set_match_level(::MatchLevel value);
  private:
  ::MatchLevel _internal_match_level() const;
  void _internal_set_match_level(::MatchLevel value);
  public:

  // uint32 match_number = 4;
  void clear_match_number();
  uint32_t match_number() const;
  void set_match_number(uint32_t value);
  private:
  uint32_t _internal_match_number() const;
  void _internal_set_match_number(uint32_t value);
  public:

  // .MatchSlot match_slot = 5;
  void clear_match_slot();
  ::MatchSlot match_slot() const;
  void set_match_slot(::MatchSlot value);
  private:
  ::MatchSlot _internal_match_slot() const;
  void _internal_set_match_slot(::MatchSlot value);
  public:

  // uint32 team_number = 6;
  void clear_team_number();
  uint32_t team_number() const;
  void set_team_number(uint32_t value);
  private:
  uint32_t _internal_team_number() const;
  void _internal_set_team_number(uint32_t value);
  public:

  // uint32 auto_start_position = 7;
  void clear_auto_start_position();
  uint32_t auto_start_position() const;
  void set_auto_start_position(uint32_t value);
  private:
  uint32_t _internal_auto_start_position() const;
  void _internal_set_auto_start_position(uint32_t value);
  public:

  // uint32 auto_fuel = 8;
  void clear_auto_fuel();
  uint32_t auto_fuel() const;
  void set_auto_fuel(uint32_t value);
  private:
  uint32_t _internal_auto_fuel() const;
  void _internal_set_auto_fuel(uint32_t value);
  public:

  // uint32 auto_neutral_zone_pass = 9;
  void clear_auto_neutral_zone_pass();
  uint32_t auto_neutral_zone_pass() const;
  void set_auto_neutral_zone_pass(uint32_t value);
  private:
  uint32_t _internal_auto_neutral_zone_pass() const;
  void _internal_set_auto_neutral_zone_pass(uint32_t value);
  public:

  // .AutoClimb auto_climb = 10;
  void clear_auto_climb();
  ::AutoClimb auto_climb() const;
  void set_auto_climb(::AutoClimb value);
  private:
  ::AutoClimb _internal_auto_climb() const;
  void _internal_set_auto_climb(::AutoClimb value);
  public:

  // bool auto_depot_pickup = 11;
  void clear_auto_depot_pickup();
  bool auto_depot_pickup() const;
  void set_auto_depot_pickup(bool value);
  private:
  bool _internal_auto_depot_pickup() const;
  void _internal_set_auto_depot_pickup(bool value);
  public:

  // bool auto_outpost_pickup = 12;
  void clear_auto_outpost_pickup();
  bool auto_outpost_pickup() const;
  void set_auto_outpost_pickup(bool value);
  private:
  bool _internal_auto_outpost_pickup() const;
  void _internal_set_auto_outpost_pickup(bool value);
  public:

  // bool auto_neutral_zone_pickup = 13;
  void clear_auto_neutral_zone_pickup();
  bool auto_neutral_zone_pickup() const;
  void set_auto_neutral_zone_pickup(bool value);
  private:
  bool _internal_auto_neutral_zone_pickup() const;
  void _internal_set_auto_neutral_zone_pickup(bool value);
  public:

  // bool teleop_depot_pickup = 18;
  void clear_teleop_depot_pickup();
  bool teleop_depot_pickup() const;
  void set_teleop_depot_pickup(bool value);
  private:
  bool _internal_teleop_depot_pickup() const;
  void _internal_set_teleop_depot_pickup(bool value);
  public:

  // uint32 teleop_shooting_locations = 14;
  void clear_teleop_shooting_locations();
  uint32_t teleop_shooting_locations() const;
  void set_teleop_shooting_locations(uint32_t value);
  private:
  uint32_t _internal_teleop_shooting_locations() const;
  void _internal_set_teleop_shooting_locations(uint32_t value);
  public:

  // uint32 teleop_fuel = 15;
  void clear_teleop_fuel();
  uint32_t teleop_fuel() const;
  void set_teleop_fuel(uint32_t value);
  private:
  uint32_t _internal_teleop_fuel() const;
  void _internal_set_teleop_fuel(uint32_t value);
  public:

  // uint32 teleop_neutral_zone_pass = 16;
  void clear_teleop_neutral_zone_pass();
  uint32_t teleop_neutral_zone_pass() const;
  void set_teleop_neutral_zone_pass(uint32_t value);
  private:
  uint32_t _internal_teleop_neutral_zone_pass() const;
  void _internal_set_teleop_neutral_zone_pass(uint32_t value);
  public:

  // uint32 teleop_opponent_zone_pass = 17;
  void clear_teleop_opponent_zone_pass();
  uint32_t teleop_opponent_zone_pass() const;
  void set_teleop_opponent_zone_pass(uint32_t value);
  private:
  uint32_t _internal_teleop_opponent_zone_pass() const;
  void _internal_set_teleop_opponent_zone_pass(uint32_t value);
  public:

  // bool teleop_outpost_pickup = 19;
  void clear_teleop_outpost_pickup();
  bool teleop_outpost_pickup() const;
  void set_teleop_outpost_pickup(bool value);
  private:
  bool _internal_teleop_outpost_pickup() const;
  void _internal_set_teleop_outpost_pickup(bool value);
  public:

  // bool teleop_neutral_zone_pickup = 20;
  void clear_teleop_neutral_zone_pickup();
  bool teleop_neutral_zone_pickup() const;
  void set_teleop_neutral_zone_pickup(bool value);
  private:
  bool _internal_teleop_neutral_zone_pickup() const;
  void _internal_set_teleop_neutral_zone_pickup(bool value);
  public:

  // bool teleop_floor_pickup = 21;
  void clear_teleop_floor_pickup();
  bool teleop_floor_pickup() const;
  void set_teleop_floor_pickup(bool value);
  private:
  bool _internal_teleop_floor_pickup() const;
  void _internal_set_teleop_floor_pickup(bool value);
  public:

  // bool crossed_bump = 26;
  void clear_crossed_bump();
  bool crossed_bump() const;
  void set_crossed_bump(bool value);
  private:
  bool _internal_crossed_bump() const;
  void _internal_set_crossed_bump(bool value);
  public:

  // .EndgameClimb endgame_climb = 22;
  void clear_endgame_climb();
  ::EndgameClimb endgame_climb() const;
  void set_endgame_climb(::EndgameClimb value);
  private:
  ::EndgameClimb _internal_endgame_climb() const;
  void _internal_set_endgame_climb(::EndgameClimb value);
  public:

  // .SkillRating driver_skill = 23;
  void clear_driver_skill();
  ::SkillRating driver_skill() const;
  void set_driver_skill(::SkillRating value);
  private:
  ::SkillRating _internal_driver_skill() const;
  void _internal_set_driver_skill(::SkillRating value);
  public:

  // .SkillRating defensive_skill = 24;
  void clear_defensive_skill();
  ::SkillRating defensive_skill() const;
  void set_defensive_skill(::SkillRating value);
  private:
  ::SkillRating _internal_defensive_skill() const;
  void _internal_set_defensive_skill(::SkillRating value);
  public:

  // .SkillRating robot_speed = 25;
  void clear_robot_speed();
  ::SkillRating robot_speed() const;
  void set_robot_speed(::SkillRating value);
  private:
  ::SkillRating _internal_robot_speed() const;
  void _internal_set_robot_speed(::SkillRating value);
  public:

  // bool crosssed_trench = 27;
  void clear_crosssed_trench();
  bool crosssed_trench() const;
  void set_crosssed_trench(bool value);
  private:
  bool _internal_crosssed_trench() const;
  void _internal_set_crosssed_trench(bool value);
  public:

  // bool immobilized = 28;
  void clear_immobilized();
  bool immobilized() const;
  void set_immobilized(bool value);
  private:
  bool _internal_immobilized() const;
  void _internal_set_immobilized(bool value);
  public:

  // bool tippy = 29;
  void clear_tippy();
  bool tippy() const;
  void set_tippy(bool value);
  private:
  bool _internal_tippy() const;
  void _internal_set_tippy(bool value);
  public:

  // bool good_partner = 30;
  void clear_good_partner();
  bool good_partner() const;
  void set_good_partner(bool value);
  private:
  bool _internal_good_partner() const;
  void _internal_set_good_partner(bool value);
  public:

  // bool was_defended = 31;
  void clear_was_defended();
  bool was_defended() const;
  void set_was_defended(bool value);
  private:
  bool _internal_was_defended() const;
  void _internal_set_was_defended(bool value);
  public:

  // bool excessive_penalties = 32;
  void clear_excessive_penalties();
  bool excessive_penalties() const;
  void set_excessive_penalties(bool value);
  private:
  bool _internal_excessive_penalties() const;
  void _internal_set_excessive_penalties(bool value);
  public:

  // uint32 fuel_percentage = 33;
  void clear_fuel_percentage();
  uint32_t fuel_percentage() const;
  void set_fuel_percentage(uint32_t value);
  private:
  uint32_t _internal_fuel_percentage() const;
  void _internal_set_fuel_percentage(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:MatchData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr scout_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr event_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr notes_;
    int match_level_;
    uint32_t match_number_;
    int match_slot_;
    uint32_t team_number_;
    uint32_t auto_start_position_;
    uint32_t auto_fuel_;
    uint32_t auto_neutral_zone_pass_;
    int auto_climb_;
    bool auto_depot_pickup_;
    bool auto_outpost_pickup_;
    bool auto_neutral_zone_pickup_;
    bool teleop_depot_pickup_;
    uint32_t teleop_shooting_locations_;
    uint32_t teleop_fuel_;
    uint32_t teleop_neutral_zone_pass_;
    uint32_t teleop_opponent_zone_pass_;
    bool teleop_outpost_pickup_;
    bool teleop_neutral_zone_pickup_;
    bool teleop_floor_pickup_;
    bool crossed_bump_;
    int endgame_climb_;
    int driver_skill_;
    int defensive_skill_;
    int robot_speed_;
    bool crosssed_trench_;
    bool immobilized_;
    bool tippy_;
    bool good_partner_;
    bool was_defended_;
    bool excessive_penalties_;
    uint32_t fuel_percentage_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scouting_5fdata_2eproto;
};
// -------------------------------------------------------------------

class CompetitionDataSet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CompetitionDataSet) */ {
 public:
  inline CompetitionDataSet() : CompetitionDataSet(nullptr) {}
  ~CompetitionDataSet() override;
  explicit PROTOBUF_CONSTEXPR CompetitionDataSet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CompetitionDataSet(const CompetitionDataSet& from);
  CompetitionDataSet(CompetitionDataSet&& from) noexcept
    : CompetitionDataSet() {
    *this = ::std::move(from);
  }

  inline CompetitionDataSet& operator=(const CompetitionDataSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompetitionDataSet& operator=(CompetitionDataSet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CompetitionDataSet& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompetitionDataSet* internal_default_instance() {
    return reinterpret_cast<const CompetitionDataSet*>(
               &_CompetitionDataSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CompetitionDataSet& a, CompetitionDataSet& b) {
    a.Swap(&b);
  }
  inline void Swap(CompetitionDataSet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompetitionDataSet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompetitionDataSet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CompetitionDataSet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CompetitionDataSet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CompetitionDataSet& from) {
    CompetitionDataSet::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompetitionDataSet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CompetitionDataSet";
  }
  protected:
  explicit CompetitionDataSet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMatchesFieldNumber = 1,
  };
  // repeated .MatchData matches = 1;
  int matches_size() const;
  private:
  int _internal_matches_size() const;
  public:
  void clear_matches();
  ::MatchData* mutable_matches(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MatchData >*
      mutable_matches();
  private:
  const ::MatchData& _internal_matches(int index) const;
  ::MatchData* _internal_add_matches();
  public:
  const ::MatchData& matches(int index) const;
  ::MatchData* add_matches();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MatchData >&
      matches() const;

  // @@protoc_insertion_point(class_scope:CompetitionDataSet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MatchData > matches_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scouting_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MatchData

// string scout_name = 1;
inline void MatchData::clear_scout_name() {
  _impl_.scout_name_.ClearToEmpty();
}
inline const std::string& MatchData::scout_name() const {
  // @@protoc_insertion_point(field_get:MatchData.scout_name)
  return _internal_scout_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MatchData::set_scout_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.scout_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MatchData.scout_name)
}
inline std::string* MatchData::mutable_scout_name() {
  std::string* _s = _internal_mutable_scout_name();
  // @@protoc_insertion_point(field_mutable:MatchData.scout_name)
  return _s;
}
inline const std::string& MatchData::_internal_scout_name() const {
  return _impl_.scout_name_.Get();
}
inline void MatchData::_internal_set_scout_name(const std::string& value) {
  
  _impl_.scout_name_.Set(value, GetArenaForAllocation());
}
inline std::string* MatchData::_internal_mutable_scout_name() {
  
  return _impl_.scout_name_.Mutable(GetArenaForAllocation());
}
inline std::string* MatchData::release_scout_name() {
  // @@protoc_insertion_point(field_release:MatchData.scout_name)
  return _impl_.scout_name_.Release();
}
inline void MatchData::set_allocated_scout_name(std::string* scout_name) {
  if (scout_name != nullptr) {
    
  } else {
    
  }
  _impl_.scout_name_.SetAllocated(scout_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.scout_name_.IsDefault()) {
    _impl_.scout_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MatchData.scout_name)
}

// string event_name = 2;
inline void MatchData::clear_event_name() {
  _impl_.event_name_.ClearToEmpty();
}
inline const std::string& MatchData::event_name() const {
  // @@protoc_insertion_point(field_get:MatchData.event_name)
  return _internal_event_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MatchData::set_event_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.event_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MatchData.event_name)
}
inline std::string* MatchData::mutable_event_name() {
  std::string* _s = _internal_mutable_event_name();
  // @@protoc_insertion_point(field_mutable:MatchData.event_name)
  return _s;
}
inline const std::string& MatchData::_internal_event_name() const {
  return _impl_.event_name_.Get();
}
inline void MatchData::_internal_set_event_name(const std::string& value) {
  
  _impl_.event_name_.Set(value, GetArenaForAllocation());
}
inline std::string* MatchData::_internal_mutable_event_name() {
  
  return _impl_.event_name_.Mutable(GetArenaForAllocation());
}
inline std::string* MatchData::release_event_name() {
  // @@protoc_insertion_point(field_release:MatchData.event_name)
  return _impl_.event_name_.Release();
}
inline void MatchData::set_allocated_event_name(std::string* event_name) {
  if (event_name != nullptr) {
    
  } else {
    
  }
  _impl_.event_name_.SetAllocated(event_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.event_name_.IsDefault()) {
    _impl_.event_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MatchData.event_name)
}

// .MatchLevel match_level = 3;
inline void MatchData::clear_match_level() {
  _impl_.match_level_ = 0;
}
inline ::MatchLevel MatchData::_internal_match_level() const {
  return static_cast< ::MatchLevel >(_impl_.match_level_);
}
inline ::MatchLevel MatchData::match_level() const {
  // @@protoc_insertion_point(field_get:MatchData.match_level)
  return _internal_match_level();
}
inline void MatchData::_internal_set_match_level(::MatchLevel value) {
  
  _impl_.match_level_ = value;
}
inline void MatchData::set_match_level(::MatchLevel value) {
  _internal_set_match_level(value);
  // @@protoc_insertion_point(field_set:MatchData.match_level)
}

// uint32 match_number = 4;
inline void MatchData::clear_match_number() {
  _impl_.match_number_ = 0u;
}
inline uint32_t MatchData::_internal_match_number() const {
  return _impl_.match_number_;
}
inline uint32_t MatchData::match_number() const {
  // @@protoc_insertion_point(field_get:MatchData.match_number)
  return _internal_match_number();
}
inline void MatchData::_internal_set_match_number(uint32_t value) {
  
  _impl_.match_number_ = value;
}
inline void MatchData::set_match_number(uint32_t value) {
  _internal_set_match_number(value);
  // @@protoc_insertion_point(field_set:MatchData.match_number)
}

// .MatchSlot match_slot = 5;
inline void MatchData::clear_match_slot() {
  _impl_.match_slot_ = 0;
}
inline ::MatchSlot MatchData::_internal_match_slot() const {
  return static_cast< ::MatchSlot >(_impl_.match_slot_);
}
inline ::MatchSlot MatchData::match_slot() const {
  // @@protoc_insertion_point(field_get:MatchData.match_slot)
  return _internal_match_slot();
}
inline void MatchData::_internal_set_match_slot(::MatchSlot value) {
  
  _impl_.match_slot_ = value;
}
inline void MatchData::set_match_slot(::MatchSlot value) {
  _internal_set_match_slot(value);
  // @@protoc_insertion_point(field_set:MatchData.match_slot)
}

// uint32 team_number = 6;
inline void MatchData::clear_team_number() {
  _impl_.team_number_ = 0u;
}
inline uint32_t MatchData::_internal_team_number() const {
  return _impl_.team_number_;
}
inline uint32_t MatchData::team_number() const {
  // @@protoc_insertion_point(field_get:MatchData.team_number)
  return _internal_team_number();
}
inline void MatchData::_internal_set_team_number(uint32_t value) {
  
  _impl_.team_number_ = value;
}
inline void MatchData::set_team_number(uint32_t value) {
  _internal_set_team_number(value);
  // @@protoc_insertion_point(field_set:MatchData.team_number)
}

// uint32 auto_start_position = 7;
inline void MatchData::clear_auto_start_position() {
  _impl_.auto_start_position_ = 0u;
}
inline uint32_t MatchData::_internal_auto_start_position() const {
  return _impl_.auto_start_position_;
}
inline uint32_t MatchData::auto_start_position() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_start_position)
  return _internal_auto_start_position();
}
inline void MatchData::_internal_set_auto_start_position(uint32_t value) {
  
  _impl_.auto_start_position_ = value;
}
inline void MatchData::set_auto_start_position(uint32_t value) {
  _internal_set_auto_start_position(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_start_position)
}

// uint32 auto_fuel = 8;
inline void MatchData::clear_auto_fuel() {
  _impl_.auto_fuel_ = 0u;
}
inline uint32_t MatchData::_internal_auto_fuel() const {
  return _impl_.auto_fuel_;
}
inline uint32_t MatchData::auto_fuel() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_fuel)
  return _internal_auto_fuel();
}
inline void MatchData::_internal_set_auto_fuel(uint32_t value) {
  
  _impl_.auto_fuel_ = value;
}
inline void MatchData::set_auto_fuel(uint32_t value) {
  _internal_set_auto_fuel(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_fuel)
}

// uint32 auto_neutral_zone_pass = 9;
inline void MatchData::clear_auto_neutral_zone_pass() {
  _impl_.auto_neutral_zone_pass_ = 0u;
}
inline uint32_t MatchData::_internal_auto_neutral_zone_pass() const {
  return _impl_.auto_neutral_zone_pass_;
}
inline uint32_t MatchData::auto_neutral_zone_pass() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_neutral_zone_pass)
  return _internal_auto_neutral_zone_pass();
}
inline void MatchData::_internal_set_auto_neutral_zone_pass(uint32_t value) {
  
  _impl_.auto_neutral_zone_pass_ = value;
}
inline void MatchData::set_auto_neutral_zone_pass(uint32_t value) {
  _internal_set_auto_neutral_zone_pass(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_neutral_zone_pass)
}

// .AutoClimb auto_climb = 10;
inline void MatchData::clear_auto_climb() {
  _impl_.auto_climb_ = 0;
}
inline ::AutoClimb MatchData::_internal_auto_climb() const {
  return static_cast< ::AutoClimb >(_impl_.auto_climb_);
}
inline ::AutoClimb MatchData::auto_climb() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_climb)
  return _internal_auto_climb();
}
inline void MatchData::_internal_set_auto_climb(::AutoClimb value) {
  
  _impl_.auto_climb_ = value;
}
inline void MatchData::set_auto_climb(::AutoClimb value) {
  _internal_set_auto_climb(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_climb)
}

// bool auto_depot_pickup = 11;
inline void MatchData::clear_auto_depot_pickup() {
  _impl_.auto_depot_pickup_ = false;
}
inline bool MatchData::_internal_auto_depot_pickup() const {
  return _impl_.auto_depot_pickup_;
}
inline bool MatchData::auto_depot_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_depot_pickup)
  return _internal_auto_depot_pickup();
}
inline void MatchData::_internal_set_auto_depot_pickup(bool value) {
  
  _impl_.auto_depot_pickup_ = value;
}
inline void MatchData::set_auto_depot_pickup(bool value) {
  _internal_set_auto_depot_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_depot_pickup)
}

// bool auto_outpost_pickup = 12;
inline void MatchData::clear_auto_outpost_pickup() {
  _impl_.auto_outpost_pickup_ = false;
}
inline bool MatchData::_internal_auto_outpost_pickup() const {
  return _impl_.auto_outpost_pickup_;
}
inline bool MatchData::auto_outpost_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_outpost_pickup)
  return _internal_auto_outpost_pickup();
}
inline void MatchData::_internal_set_auto_outpost_pickup(bool value) {
  
  _impl_.auto_outpost_pickup_ = value;
}
inline void MatchData::set_auto_outpost_pickup(bool value) {
  _internal_set_auto_outpost_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_outpost_pickup)
}

// bool auto_neutral_zone_pickup = 13;
inline void MatchData::clear_auto_neutral_zone_pickup() {
  _impl_.auto_neutral_zone_pickup_ = false;
}
inline bool MatchData::_internal_auto_neutral_zone_pickup() const {
  return _impl_.auto_neutral_zone_pickup_;
}
inline bool MatchData::auto_neutral_zone_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.auto_neutral_zone_pickup)
  return _internal_auto_neutral_zone_pickup();
}
inline void MatchData::_internal_set_auto_neutral_zone_pickup(bool value) {
  
  _impl_.auto_neutral_zone_pickup_ = value;
}
inline void MatchData::set_auto_neutral_zone_pickup(bool value) {
  _internal_set_auto_neutral_zone_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.auto_neutral_zone_pickup)
}

// uint32 teleop_shooting_locations = 14;
inline void MatchData::clear_teleop_shooting_locations() {
  _impl_.teleop_shooting_locations_ = 0u;
}
inline uint32_t MatchData::_internal_teleop_shooting_locations() const {
  return _impl_.teleop_shooting_locations_;
}
inline uint32_t MatchData::teleop_shooting_locations() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_shooting_locations)
  return _internal_teleop_shooting_locations();
}
inline void MatchData::_internal_set_teleop_shooting_locations(uint32_t value) {
  
  _impl_.teleop_shooting_locations_ = value;
}
inline void MatchData::set_teleop_shooting_locations(uint32_t value) {
  _internal_set_teleop_shooting_locations(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_shooting_locations)
}

// uint32 teleop_fuel = 15;
inline void MatchData::clear_teleop_fuel() {
  _impl_.teleop_fuel_ = 0u;
}
inline uint32_t MatchData::_internal_teleop_fuel() const {
  return _impl_.teleop_fuel_;
}
inline uint32_t MatchData::teleop_fuel() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_fuel)
  return _internal_teleop_fuel();
}
inline void MatchData::_internal_set_teleop_fuel(uint32_t value) {
  
  _impl_.teleop_fuel_ = value;
}
inline void MatchData::set_teleop_fuel(uint32_t value) {
  _internal_set_teleop_fuel(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_fuel)
}

// uint32 teleop_neutral_zone_pass = 16;
inline void MatchData::clear_teleop_neutral_zone_pass() {
  _impl_.teleop_neutral_zone_pass_ = 0u;
}
inline uint32_t MatchData::_internal_teleop_neutral_zone_pass() const {
  return _impl_.teleop_neutral_zone_pass_;
}
inline uint32_t MatchData::teleop_neutral_zone_pass() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_neutral_zone_pass)
  return _internal_teleop_neutral_zone_pass();
}
inline void MatchData::_internal_set_teleop_neutral_zone_pass(uint32_t value) {
  
  _impl_.teleop_neutral_zone_pass_ = value;
}
inline void MatchData::set_teleop_neutral_zone_pass(uint32_t value) {
  _internal_set_teleop_neutral_zone_pass(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_neutral_zone_pass)
}

// uint32 teleop_opponent_zone_pass = 17;
inline void MatchData::clear_teleop_opponent_zone_pass() {
  _impl_.teleop_opponent_zone_pass_ = 0u;
}
inline uint32_t MatchData::_internal_teleop_opponent_zone_pass() const {
  return _impl_.teleop_opponent_zone_pass_;
}
inline uint32_t MatchData::teleop_opponent_zone_pass() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_opponent_zone_pass)
  return _internal_teleop_opponent_zone_pass();
}
inline void MatchData::_internal_set_teleop_opponent_zone_pass(uint32_t value) {
  
  _impl_.teleop_opponent_zone_pass_ = value;
}
inline void MatchData::set_teleop_opponent_zone_pass(uint32_t value) {
  _internal_set_teleop_opponent_zone_pass(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_opponent_zone_pass)
}

// bool teleop_depot_pickup = 18;
inline void MatchData::clear_teleop_depot_pickup() {
  _impl_.teleop_depot_pickup_ = false;
}
inline bool MatchData::_internal_teleop_depot_pickup() const {
  return _impl_.teleop_depot_pickup_;
}
inline bool MatchData::teleop_depot_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_depot_pickup)
  return _internal_teleop_depot_pickup();
}
inline void MatchData::_internal_set_teleop_depot_pickup(bool value) {
  
  _impl_.teleop_depot_pickup_ = value;
}
inline void MatchData::set_teleop_depot_pickup(bool value) {
  _internal_set_teleop_depot_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_depot_pickup)
}

// bool teleop_outpost_pickup = 19;
inline void MatchData::clear_teleop_outpost_pickup() {
  _impl_.teleop_outpost_pickup_ = false;
}
inline bool MatchData::_internal_teleop_outpost_pickup() const {
  return _impl_.teleop_outpost_pickup_;
}
inline bool MatchData::teleop_outpost_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_outpost_pickup)
  return _internal_teleop_outpost_pickup();
}
inline void MatchData::_internal_set_teleop_outpost_pickup(bool value) {
  
  _impl_.teleop_outpost_pickup_ = value;
}
inline void MatchData::set_teleop_outpost_pickup(bool value) {
  _internal_set_teleop_outpost_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_outpost_pickup)
}

// bool teleop_neutral_zone_pickup = 20;
inline void MatchData::clear_teleop_neutral_zone_pickup() {
  _impl_.teleop_neutral_zone_pickup_ = false;
}
inline bool MatchData::_internal_teleop_neutral_zone_pickup() const {
  return _impl_.teleop_neutral_zone_pickup_;
}
inline bool MatchData::teleop_neutral_zone_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_neutral_zone_pickup)
  return _internal_teleop_neutral_zone_pickup();
}
inline void MatchData::_internal_set_teleop_neutral_zone_pickup(bool value) {
  
  _impl_.teleop_neutral_zone_pickup_ = value;
}
inline void MatchData::set_teleop_neutral_zone_pickup(bool value) {
  _internal_set_teleop_neutral_zone_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_neutral_zone_pickup)
}

// bool teleop_floor_pickup = 21;
inline void MatchData::clear_teleop_floor_pickup() {
  _impl_.teleop_floor_pickup_ = false;
}
inline bool MatchData::_internal_teleop_floor_pickup() const {
  return _impl_.teleop_floor_pickup_;
}
inline bool MatchData::teleop_floor_pickup() const {
  // @@protoc_insertion_point(field_get:MatchData.teleop_floor_pickup)
  return _internal_teleop_floor_pickup();
}
inline void MatchData::_internal_set_teleop_floor_pickup(bool value) {
  
  _impl_.teleop_floor_pickup_ = value;
}
inline void MatchData::set_teleop_floor_pickup(bool value) {
  _internal_set_teleop_floor_pickup(value);
  // @@protoc_insertion_point(field_set:MatchData.teleop_floor_pickup)
}

// .EndgameClimb endgame_climb = 22;
inline void MatchData::clear_endgame_climb() {
  _impl_.endgame_climb_ = 0;
}
inline ::EndgameClimb MatchData::_internal_endgame_climb() const {
  return static_cast< ::EndgameClimb >(_impl_.endgame_climb_);
}
inline ::EndgameClimb MatchData::endgame_climb() const {
  // @@protoc_insertion_point(field_get:MatchData.endgame_climb)
  return _internal_endgame_climb();
}
inline void MatchData::_internal_set_endgame_climb(::EndgameClimb value) {
  
  _impl_.endgame_climb_ = value;
}
inline void MatchData::set_endgame_climb(::EndgameClimb value) {
  _internal_set_endgame_climb(value);
  // @@protoc_insertion_point(field_set:MatchData.endgame_climb)
}

// .SkillRating driver_skill = 23;
inline void MatchData::clear_driver_skill() {
  _impl_.driver_skill_ = 0;
}
inline ::SkillRating MatchData::_internal_driver_skill() const {
  return static_cast< ::SkillRating >(_impl_.driver_skill_);
}
inline ::SkillRating MatchData::driver_skill() const {
  // @@protoc_insertion_point(field_get:MatchData.driver_skill)
  return _internal_driver_skill();
}
inline void MatchData::_internal_set_driver_skill(::SkillRating value) {
  
  _impl_.driver_skill_ = value;
}
inline void MatchData::set_driver_skill(::SkillRating value) {
  _internal_set_driver_skill(value);
  // @@protoc_insertion_point(field_set:MatchData.driver_skill)
}

// .SkillRating defensive_skill = 24;
inline void MatchData::clear_defensive_skill() {
  _impl_.defensive_skill_ = 0;
}
inline ::SkillRating MatchData::_internal_defensive_skill() const {
  return static_cast< ::SkillRating >(_impl_.defensive_skill_);
}
inline ::SkillRating MatchData::defensive_skill() const {
  // @@protoc_insertion_point(field_get:MatchData.defensive_skill)
  return _internal_defensive_skill();
}
inline void MatchData::_internal_set_defensive_skill(::SkillRating value) {
  
  _impl_.defensive_skill_ = value;
}
inline void MatchData::set_defensive_skill(::SkillRating value) {
  _internal_set_defensive_skill(value);
  // @@protoc_insertion_point(field_set:MatchData.defensive_skill)
}

// .SkillRating robot_speed = 25;
inline void MatchData::clear_robot_speed() {
  _impl_.robot_speed_ = 0;
}
inline ::SkillRating MatchData::_internal_robot_speed() const {
  return static_cast< ::SkillRating >(_impl_.robot_speed_);
}
inline ::SkillRating MatchData::robot_speed() const {
  // @@protoc_insertion_point(field_get:MatchData.robot_speed)
  return _internal_robot_speed();
}
inline void MatchData::_internal_set_robot_speed(::SkillRating value) {
  
  _impl_.robot_speed_ = value;
}
inline void MatchData::set_robot_speed(::SkillRating value) {
  _internal_set_robot_speed(value);
  // @@protoc_insertion_point(field_set:MatchData.robot_speed)
}

// bool crossed_bump = 26;
inline void MatchData::clear_crossed_bump() {
  _impl_.crossed_bump_ = false;
}
inline bool MatchData::_internal_crossed_bump() const {
  return _impl_.crossed_bump_;
}
inline bool MatchData::crossed_bump() const {
  // @@protoc_insertion_point(field_get:MatchData.crossed_bump)
  return _internal_crossed_bump();
}
inline void MatchData::_internal_set_crossed_bump(bool value) {
  
  _impl_.crossed_bump_ = value;
}
inline void MatchData::set_crossed_bump(bool value) {
  _internal_set_crossed_bump(value);
  // @@protoc_insertion_point(field_set:MatchData.crossed_bump)
}

// bool crosssed_trench = 27;
inline void MatchData::clear_crosssed_trench() {
  _impl_.crosssed_trench_ = false;
}
inline bool MatchData::_internal_crosssed_trench() const {
  return _impl_.crosssed_trench_;
}
inline bool MatchData::crosssed_trench() const {
  // @@protoc_insertion_point(field_get:MatchData.crosssed_trench)
  return _internal_crosssed_trench();
}
inline void MatchData::_internal_set_crosssed_trench(bool value) {
  
  _impl_.crosssed_trench_ = value;
}
inline void MatchData::set_crosssed_trench(bool value) {
  _internal_set_crosssed_trench(value);
  // @@protoc_insertion_point(field_set:MatchData.crosssed_trench)
}

// bool immobilized = 28;
inline void MatchData::clear_immobilized() {
  _impl_.immobilized_ = false;
}
inline bool MatchData::_internal_immobilized() const {
  return _impl_.immobilized_;
}
inline bool MatchData::immobilized() const {
  // @@protoc_insertion_point(field_get:MatchData.immobilized)
  return _internal_immobilized();
}
inline void MatchData::_internal_set_immobilized(bool value) {
  
  _impl_.immobilized_ = value;
}
inline void MatchData::set_immobilized(bool value) {
  _internal_set_immobilized(value);
  // @@protoc_insertion_point(field_set:MatchData.immobilized)
}

// bool tippy = 29;
inline void MatchData::clear_tippy() {
  _impl_.tippy_ = false;
}
inline bool MatchData::_internal_tippy() const {
  return _impl_.tippy_;
}
inline bool MatchData::tippy() const {
  // @@protoc_insertion_point(field_get:MatchData.tippy)
  return _internal_tippy();
}
inline void MatchData::_internal_set_tippy(bool value) {
  
  _impl_.tippy_ = value;
}
inline void MatchData::set_tippy(bool value) {
  _internal_set_tippy(value);
  // @@protoc_insertion_point(field_set:MatchData.tippy)
}

// bool good_partner = 30;
inline void MatchData::clear_good_partner() {
  _impl_.good_partner_ = false;
}
inline bool MatchData::_internal_good_partner() const {
  return _impl_.good_partner_;
}
inline bool MatchData::good_partner() const {
  // @@protoc_insertion_point(field_get:MatchData.good_partner)
  return _internal_good_partner();
}
inline void MatchData::_internal_set_good_partner(bool value) {
  
  _impl_.good_partner_ = value;
}
inline void MatchData::set_good_partner(bool value) {
  _internal_set_good_partner(value);
  // @@protoc_insertion_point(field_set:MatchData.good_partner)
}

// bool was_defended = 31;
inline void MatchData::clear_was_defended() {
  _impl_.was_defended_ = false;
}
inline bool MatchData::_internal_was_defended() const {
  return _impl_.was_defended_;
}
inline bool MatchData::was_defended() const {
  // @@protoc_insertion_point(field_get:MatchData.was_defended)
  return _internal_was_defended();
}
inline void MatchData::_internal_set_was_defended(bool value) {
  
  _impl_.was_defended_ = value;
}
inline void MatchData::set_was_defended(bool value) {
  _internal_set_was_defended(value);
  // @@protoc_insertion_point(field_set:MatchData.was_defended)
}

// bool excessive_penalties = 32;
inline void MatchData::clear_excessive_penalties() {
  _impl_.excessive_penalties_ = false;
}
inline bool MatchData::_internal_excessive_penalties() const {
  return _impl_.excessive_penalties_;
}
inline bool MatchData::excessive_penalties() const {
  // @@protoc_insertion_point(field_get:MatchData.excessive_penalties)
  return _internal_excessive_penalties();
}
inline void MatchData::_internal_set_excessive_penalties(bool value) {
  
  _impl_.excessive_penalties_ = value;
}
inline void MatchData::set_excessive_penalties(bool value) {
  _internal_set_excessive_penalties(value);
  // @@protoc_insertion_point(field_set:MatchData.excessive_penalties)
}

// uint32 fuel_percentage = 33;
inline void MatchData::clear_fuel_percentage() {
  _impl_.fuel_percentage_ = 0u;
}
inline uint32_t MatchData::_internal_fuel_percentage() const {
  return _impl_.fuel_percentage_;
}
inline uint32_t MatchData::fuel_percentage() const {
  // @@protoc_insertion_point(field_get:MatchData.fuel_percentage)
  return _internal_fuel_percentage();
}
inline void MatchData::_internal_set_fuel_percentage(uint32_t value) {
  
  _impl_.fuel_percentage_ = value;
}
inline void MatchData::set_fuel_percentage(uint32_t value) {
  _internal_set_fuel_percentage(value);
  // @@protoc_insertion_point(field_set:MatchData.fuel_percentage)
}

// string notes = 34;
inline void MatchData::clear_notes() {
  _impl_.notes_.ClearToEmpty();
}
inline const std::string& MatchData::notes() const {
  // @@protoc_insertion_point(field_get:MatchData.notes)
  return _internal_notes();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MatchData::set_notes(ArgT0&& arg0, ArgT... args) {
 
 _impl_.notes_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MatchData.notes)
}
inline std::string* MatchData::mutable_notes() {
  std::string* _s = _internal_mutable_notes();
  // @@protoc_insertion_point(field_mutable:MatchData.notes)
  return _s;
}
inline const std::string& MatchData::_internal_notes() const {
  return _impl_.notes_.Get();
}
inline void MatchData::_internal_set_notes(const std::string& value) {
  
  _impl_.notes_.Set(value, GetArenaForAllocation());
}
inline std::string* MatchData::_internal_mutable_notes() {
  
  return _impl_.notes_.Mutable(GetArenaForAllocation());
}
inline std::string* MatchData::release_notes() {
  // @@protoc_insertion_point(field_release:MatchData.notes)
  return _impl_.notes_.Release();
}
inline void MatchData::set_allocated_notes(std::string* notes) {
  if (notes != nullptr) {
    
  } else {
    
  }
  _impl_.notes_.SetAllocated(notes, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.notes_.IsDefault()) {
    _impl_.notes_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MatchData.notes)
}

// -------------------------------------------------------------------

// CompetitionDataSet

// repeated .MatchData matches = 1;
inline int CompetitionDataSet::_internal_matches_size() const {
  return _impl_.matches_.size();
}
inline int CompetitionDataSet::matches_size() const {
  return _internal_matches_size();
}
inline void CompetitionDataSet::clear_matches() {
  _impl_.matches_.Clear();
}
inline ::MatchData* CompetitionDataSet::mutable_matches(int index) {
  // @@protoc_insertion_point(field_mutable:CompetitionDataSet.matches)
  return _impl_.matches_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MatchData >*
CompetitionDataSet::mutable_matches() {
  // @@protoc_insertion_point(field_mutable_list:CompetitionDataSet.matches)
  return &_impl_.matches_;
}
inline const ::MatchData& CompetitionDataSet::_internal_matches(int index) const {
  return _impl_.matches_.Get(index);
}
inline const ::MatchData& CompetitionDataSet::matches(int index) const {
  // @@protoc_insertion_point(field_get:CompetitionDataSet.matches)
  return _internal_matches(index);
}
inline ::MatchData* CompetitionDataSet::_internal_add_matches() {
  return _impl_.matches_.Add();
}
inline ::MatchData* CompetitionDataSet::add_matches() {
  ::MatchData* _add = _internal_add_matches();
  // @@protoc_insertion_point(field_add:CompetitionDataSet.matches)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MatchData >&
CompetitionDataSet::matches() const {
  // @@protoc_insertion_point(field_list:CompetitionDataSet.matches)
  return _impl_.matches_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::MatchSlot> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MatchSlot>() {
  return ::MatchSlot_descriptor();
}
template <> struct is_proto_enum< ::MatchLevel> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MatchLevel>() {
  return ::MatchLevel_descriptor();
}
template <> struct is_proto_enum< ::AutoClimb> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::AutoClimb>() {
  return ::AutoClimb_descriptor();
}
template <> struct is_proto_enum< ::EndgameClimb> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EndgameClimb>() {
  return ::EndgameClimb_descriptor();
}
template <> struct is_proto_enum< ::SkillRating> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SkillRating>() {
  return ::SkillRating_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_scouting_5fdata_2eproto
